# Generated by Django 2.2.3 on 2019-07-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("address", models.CharField(max_length=100, null=True)),
                ("siret", models.CharField(max_length=100, null=True)),
                ("code", models.IntegerField(null=True)),
                ("created", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("date_of_birth", models.CharField(max_length=100, null=True)),
                (
                    "companies",
                    models.ManyToManyField(
                        related_name="companies", to="verif_parser.Company"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="company",
            name="directors",
            field=models.ManyToManyField(
                related_name="directors", to="verif_parser.Director"
            ),
        ),
    ]
