# Generated by Django 2.2.3 on 2019-07-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("verif_parser", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="company",
            name="siren",
            field=models.IntegerField(default=2),
            preserve_default=False,
        )
    ]
