# Generated by Django 2.2.3 on 2019-07-08 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verif_parser', '0002_company_siren'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='siren',
        ),
    ]
