# Generated by Django 2.2.3 on 2019-07-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verif_parser', '0005_auto_20190710_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='siren',
            field=models.IntegerField(),
        ),
    ]
